[build-system]
requires = ["setuptools>=61.0"]

[project]
dynamic = ["version"]
requires-python = ">=3.10"
name = "Summative"

[project.optional-dependencies]
dev = ["pytest"]

[tool.pytest.ini_options]
pythonpath = [".", "src"]
